[package]
name = "wsm"
description = "Cilki's WorkSpace Manager"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/cilki/wsm/"

[dependencies]
clap = { version = "4", features = ["derive"] }
toml = "0"
serde = { version = "1", features = ["derive"] }
git-repository = "0"
walkdir = "2"
cmd_lib = "1.3.0"
regex = "1"
log = "0.4.17"
env_logger = "0.10.0"
simple-error = "0.2.3"
